<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="5" passed="4" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2022-05-22T14:54:11 BST" name="Suite" finished-at="2022-05-22T14:54:14 BST" duration-ms="3123">
    <groups>
    </groups>
    <test started-at="2022-05-22T14:54:11 BST" name="Test" finished-at="2022-05-22T14:54:14 BST" duration-ms="3123">
      <class name="testCases.TC_ResReqAPI">
        <test-method signature="getAllUsers()[pri:1, instance:testCases.TC_ResReqAPI@7b227d8d]" started-at="2022-05-22T14:54:11 BST" name="getAllUsers" finished-at="2022-05-22T14:54:13 BST" duration-ms="1998" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getAllUsers -->
        <test-method signature="addUser()[pri:2, instance:testCases.TC_ResReqAPI@7b227d8d]" started-at="2022-05-22T14:54:13 BST" name="addUser" finished-at="2022-05-22T14:54:14 BST" duration-ms="514" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- addUser -->
        <test-method signature="updateUser()[pri:3, instance:testCases.TC_ResReqAPI@7b227d8d]" started-at="2022-05-22T14:54:14 BST" name="updateUser" finished-at="2022-05-22T14:54:14 BST" duration-ms="199" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- updateUser -->
        <test-method signature="patchUser()[pri:4, instance:testCases.TC_ResReqAPI@7b227d8d]" started-at="2022-05-22T14:54:14 BST" name="patchUser" finished-at="2022-05-22T14:54:14 BST" duration-ms="176" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected:<true> but was:<updatedAt>]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected:<true> but was:<updatedAt>
at org.junit.Assert.fail(Assert.java:93)
at org.junit.Assert.failNotEquals(Assert.java:647)
at org.junit.Assert.assertEquals(Assert.java:128)
at org.junit.Assert.assertEquals(Assert.java:147)
at testCases.TC_ResReqAPI.patchUser(TC_ResReqAPI.java:91)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:962)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:806)
at org.testng.TestRunner.run(TestRunner.java:601)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:433)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:427)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:387)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- patchUser -->
        <test-method signature="deleteUser()[pri:5, instance:testCases.TC_ResReqAPI@7b227d8d]" started-at="2022-05-22T14:54:14 BST" name="deleteUser" finished-at="2022-05-22T14:54:14 BST" duration-ms="168" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- deleteUser -->
      </class> <!-- testCases.TC_ResReqAPI -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
